### PR TITLE
Feature/private events

### PR DESCRIPTION
**Pull request by German-Cobian**
This app allows users to host events, make invites and also accept invites from other users. 
*The front end ( `http://localhost:3000/` ) displays the list of all events, categorized by upcoming and past ones. 
*Only signed-in users can register to events. 
*When Logged-in, a user can create events and view events. 
*Every logged-in user can invite other users to an event. 
*The invited user has the option to accept the invitation or to ignore it.

### CODE REVIEW

**Review by enaburekhan — COMMENTED** [review]
# Status: Invalid
**Hi team!
Friendly reminder. The Project has to pass linter checks before it can be reviewed. Kindly fix this before submitting for a new review. This project will be marked invalid in your dashboard.**


Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Review by henatan99 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:

Hi there, you did a fantastic job on this project. :medal_sports: :clap: 

## To Highlight 
- Your app displays all the functionalities described in the requirements 
- Many aspects of the Models' associations are great and I don't get any anomaly, but you can work on following best practices 
- 

## To Improve
-  It is better to use has_and_belongs_to_many :attended_events, class_name: "Event" for User Event models association instead of using a scope method reservation_yes_past. This will help you follow best practices in associations. 
- You can check the link below for great options in associations 
[Associations](https://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many)
- Your PR summary should be short and descriptive. It is recommended if you use bullets short sentences 
- You also need to improve on your commit messages as they have to be short and descriptive

### Kindly, fix the requested changes and submit for another review

Should you have any queries, don't hesitate to find me on:
[LinkedIn](https://www.linkedin.com/in/henok-mekonnen/) | [Twitter](https://twitter.com/henatan99) | Henok Mekonnen on Slack

## Happy Coding :computer:

**Review by mricanho — CHANGES_REQUESTED** [review]
# 🔴  Changes Required 🔴  

Hello @German-Cobian @German-Cobian, unfortunately, your app is broken, you need to fix this before applying for a new review the problem is...

WhatsApp Image 2021-05-05 at 11 00 24

This way to call bootstrap works if you add the bootstrap gem, but check [this article](https://www.digitalocean.com/community/tutorials/how-to-add-bootstrap-to-a-ruby-on-rails-application) for a better result.

After that, you have another problem with the ActionView:

image

Fix this, and submit a new code review. You got this.

You can contact me on slack if you have any questions just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!👨🏽‍💻  🖥️

**Review by henatan99 — APPROVED** [review]
# Project Approved :100: 
### Hi team, congratulations! You project is approved. :champagne: :medal_sports: :clap: 

You did a great effort in your project and it is working very well.

As an OPTIONAL improvement, you can make your project follow best practices as much as possible. To help you with that, please go through this great resource on Associations, b hitting the line below:
[Rails Associations](https://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many) 

## Happy Coding :computer:

**Pull request merged**
